language: java

jdk:
  - openjdk16

env:
  global:
    - CODECOV_TOKEN="a066122f-cc80-4b7e-9b3f-f018b312f43b"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vit-chembaev@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
